spring:
  datasource:
      url: jdbc:mysql://localhost:3306/nrlee
      username: root
      password: leenari1004!!
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect